## Numpy Basics

### 1. Element wise multiplication

In [6]:
list1=[23.2,43.3,342.5,65.7,33.8]

In [7]:
list2=[89.65,4.2,34.34,64.32,54.56]

In [11]:
print(list1[0]*list2[0])
print(len(list2))

2079.88
5


In [23]:
outp=[]
for i in range(0,len(list1)):
    outp.append((list1[i]*list2[i]))


In [24]:
outp

[2079.88, 181.85999999999999, 11761.45, 4225.824, 1844.128]

### 2.With Numpy

In [25]:
import numpy as np

In [26]:
list1=np.array([432.5,423.6,34.3,456.3])

In [27]:
list2=np.array([342.2,23.2,324.3,87.8])

In [28]:
print(list1*list2)

[148001.5    9827.52  11123.49  40063.14]


### 3. In Place operations

In [32]:
list1=[1,2,3,4,5]

In [33]:
print(list1*6)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [34]:
print(list1 + list1)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


### 4.Memory effecient

In [35]:
list1=range(100000)

In [36]:
import sys

In [37]:
print(sys.getsizeof(1)*len(list1))

2800000


#### With Numpy

In [49]:
list1=np.arange(100000)

In [50]:
list1.dtype

dtype('int32')

In [51]:
z=np.array([1,2,3],dtype=np.int64)

In [52]:
z.itemsize

8

In [53]:
z.dtype

dtype('int64')

In [54]:
size=list1.size*list1.itemsize
print(size)

400000


## 5.Numpy arrays are faster

In [55]:
import time

In [56]:
size=1000000

In [57]:
l1=range(size)          # Regular lists
l2=range(size)

In [58]:
a1=np.arange(size)          # Numpy lists
a2=np.arange(size)

#### add two lists and check time

In [60]:
start=time.time()
result=[(x+y) for x,y in zip(l1,l2)]
print("normal list",(time.time()-start)*1000)

normal list 110.46886444091797


In [61]:
start=time.time()
result=a1+a2
print("numpy list",(time.time()-start)*1000)

numpy list 13.686418533325195


## 6.Basic Functions

In [62]:
l=np.zeros([2,2])

In [63]:
l

array([[0., 0.],
       [0., 0.]])

In [64]:
m=np.ones([2,2])

In [65]:
m

array([[1., 1.],
       [1., 1.]])

#### Use slicing

In [66]:
data=np.random.random((3,4))

In [67]:
data

array([[0.80408799, 0.99257969, 0.79546663, 0.09208533],
       [0.3086085 , 0.70005957, 0.191537  , 0.20872539],
       [0.80895153, 0.50269175, 0.63655979, 0.71525197]])

In [68]:
data[0]

array([0.80408799, 0.99257969, 0.79546663, 0.09208533])

In [69]:
data[0][0]

0.8040879937494503

In [70]:
data[1:]

array([[0.3086085 , 0.70005957, 0.191537  , 0.20872539],
       [0.80895153, 0.50269175, 0.63655979, 0.71525197]])

In [71]:
data[1:,1:2]

array([[0.70005957],
       [0.50269175]])

## 7.Statistical Analysis

In [74]:
info=np.random.random((2,3))

In [75]:
info

array([[0.72524786, 0.39336963, 0.12581927],
       [0.74638482, 0.64813569, 0.84494862]])

In [76]:
np.max(info)

0.8449486202160644

In [77]:
np.max(info,axis=0)

array([0.74638482, 0.64813569, 0.84494862])

In [78]:
np.max(info,axis=1)

array([0.72524786, 0.84494862])

### mean mode median

In [79]:
gather=np.array([1,1,1,1,1,1,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,4,4,4,4,4,4])

In [80]:
np.mean(gather)

2.4814814814814814

In [81]:
np.median(gather)

2.0

In [85]:
np.var(gather)

1.1385459533607682

In [86]:
np.std(gather)

1.067026688213921